// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd3BckDkM1SI4FF2qhqedkNwIT484_vHs',
    appId: '1:73052952477:web:cbc67a209d7b3776efc174',
    messagingSenderId: '73052952477',
    projectId: 'workii-18cb6',
    authDomain: 'workii-18cb6.firebaseapp.com',
    storageBucket: 'workii-18cb6.firebasestorage.app',
    measurementId: 'G-C3XMQ9QRN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi0F2GFdFKRO-FWQbdj4Rkc-CQibOb6Z8',
    appId: '1:73052952477:android:c011b5ed9156c07defc174',
    messagingSenderId: '73052952477',
    projectId: 'workii-18cb6',
    storageBucket: 'workii-18cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbi7dSzeTV5as_D8M2vc9hINNXhTbt1z0',
    appId: '1:73052952477:ios:6254b307168e1db7efc174',
    messagingSenderId: '73052952477',
    projectId: 'workii-18cb6',
    storageBucket: 'workii-18cb6.firebasestorage.app',
    iosClientId: '73052952477-1uu9aourishpjb2p87ivcvvkour2a8m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.worki',
  );

}